name: Bug Report
description: File a bug report
title: "[Bug]: "
assignees:
  - UlionTse
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: debug-tips
    attributes:
      label: Debug Tips
      description: To improve debug efficiency, please read [Issues of README](https://github.com/UlionTse/translators#issues) first.
      options:
        - label: I'm sure I've read this project's Issues of README.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: APP Version
      description: What version of App(or PYPI) are you running?
      placeholder: Tell us what you see!
      value: "0.0.1(example)"
    validations:
      required: true
  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of python are you running?
      options:
        - "3.9 (Default)"
        - "3.11"
        - "3.10"
        - "=3.8"
        - "<3.8"
    validations:
      required: true
  - type: dropdown
    id: runtime-environment
    attributes:
      label: Runtime Environment
      description: What runtime environment(OS) are you running?
      options:
        - "Linux CentOS (Default)"
        - "Linux Ubuntu"
        - "Windows 10"
        - "MacOS"
        - "Other"
    validations:
      required: true
  - type: input
    id: region
    attributes:
      label: Country/Region
      description: What Country(Region) are you running? (Translation services may be different in different regions)
      placeholder: Tell us what you see!
      value: "Qatar(example)"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: sh
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
      render: Markdown
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/UlionTse/translators/blob/master/LICENSE)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true